TWEAK_NAME = PXL_Battery
$(TWEAK_NAME)_FILES = PXL_Battery.xm PXL_Settings.m UIColor+colorFromHexString.m
$(TWEAK_NAME)_FRAMEWORKS = UIKit

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
